; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28106.4 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?init@OBJECT@XGK@@YAXPEAUObject@2@@Z		; XGK::OBJECT::init
PUBLIC	?setRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z	; XGK::OBJECT::setRot
PUBLIC	?preRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z	; XGK::OBJECT::preRot
PUBLIC	?postRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z	; XGK::OBJECT::postRot
PUBLIC	?setRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::setRotX
PUBLIC	?preRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::preRotX
PUBLIC	?postRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::postRotX
PUBLIC	?setRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::setRotY
PUBLIC	?preRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::preRotY
PUBLIC	?postRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::postRotY
PUBLIC	?setRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::setRotZ
PUBLIC	?preRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::preRotZ
PUBLIC	?postRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::postRotZ
PUBLIC	?setTrans@OBJECT@XGK@@YAXPEAUObject@2@PEAX@Z	; XGK::OBJECT::setTrans
PUBLIC	?trans@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z	; XGK::OBJECT::trans
PUBLIC	?setTransX@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::setTransX
PUBLIC	?transX@OBJECT@XGK@@YAXPEAUObject@2@M@Z		; XGK::OBJECT::transX
PUBLIC	?setTransY@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::setTransY
PUBLIC	?transY@OBJECT@XGK@@YAXPEAUObject@2@M@Z		; XGK::OBJECT::transY
PUBLIC	?setTransZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z	; XGK::OBJECT::setTransZ
PUBLIC	?transZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z		; XGK::OBJECT::transZ
PUBLIC	?update@OBJECT@XGK@@YAXPEAUObject@2@@Z		; XGK::OBJECT::update
PUBLIC	?update2@OBJECT@XGK@@YAXPEAUObject@2@@Z		; XGK::OBJECT::update2
PUBLIC	?update3@OBJECT@XGK@@YAXPEAUObject@2@@Z		; XGK::OBJECT::update3
PUBLIC	__real@3f800000
PUBLIC	__real@bf800000
EXTRN	?copy@VEC4@DATA@XGK@@YAXPEAX0@Z:PROC		; XGK::DATA::VEC4::copy
EXTRN	?reset@VEC4@DATA@XGK@@YAXPEAX@Z:PROC		; XGK::DATA::VEC4::reset
EXTRN	?ident@QUAT@DATA@XGK@@YAXPEAX@Z:PROC		; XGK::DATA::QUAT::ident
EXTRN	?ident@MAT4@DATA@XGK@@YAXPEAX@Z:PROC		; XGK::DATA::MAT4::ident
EXTRN	?add@VEC4@DATA@XGK@@3P6AXPEAX0@ZEA:QWORD	; XGK::DATA::VEC4::add
EXTRN	?muls@VEC4@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::VEC4::muls
EXTRN	?makeRot@QUAT@DATA@XGK@@3P6AXPEAX0M@ZEA:QWORD	; XGK::DATA::QUAT::makeRot
EXTRN	?preRot@QUAT@DATA@XGK@@3P6AXPEAX0M@ZEA:QWORD	; XGK::DATA::QUAT::preRot
EXTRN	?postRot@QUAT@DATA@XGK@@3P6AXPEAX0M@ZEA:QWORD	; XGK::DATA::QUAT::postRot
EXTRN	?makeRotX@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::QUAT::makeRotX
EXTRN	?preRotX@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::QUAT::preRotX
EXTRN	?postRotX@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::QUAT::postRotX
EXTRN	?makeRotY@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::QUAT::makeRotY
EXTRN	?preRotY@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::QUAT::preRotY
EXTRN	?postRotY@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::QUAT::postRotY
EXTRN	?makeRotZ@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::QUAT::makeRotZ
EXTRN	?preRotZ@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::QUAT::preRotZ
EXTRN	?postRotZ@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA:QWORD	; XGK::DATA::QUAT::postRotZ
EXTRN	?makeTrans@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA:QWORD	; XGK::DATA::MAT4::makeTrans
EXTRN	?preTrans@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA:QWORD	; XGK::DATA::MAT4::preTrans
EXTRN	?makeTransValue@MAT4@DATA@XGK@@3P6AXPEAX0M@ZEA:QWORD ; XGK::DATA::MAT4::makeTransValue
EXTRN	?preTransValue@MAT4@DATA@XGK@@3P6AXPEAX0M@ZEA:QWORD ; XGK::DATA::MAT4::preTransValue
EXTRN	?makeRotQuat@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA:QWORD ; XGK::DATA::MAT4::makeRotQuat
EXTRN	?preRotQuat@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA:QWORD	; XGK::DATA::MAT4::preRotQuat
EXTRN	_fltused:DWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$?init@OBJECT@XGK@@YAXPEAUObject@2@@Z DD imagerel $LN4
	DD	imagerel $LN4+37
	DD	imagerel $unwind$?init@OBJECT@XGK@@YAXPEAUObject@2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?trans@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z DD imagerel $LN4
	DD	imagerel $LN4+73
	DD	imagerel $unwind$?trans@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?update@OBJECT@XGK@@YAXPEAUObject@2@@Z DD imagerel $LN4
	DD	imagerel $LN4+38
	DD	imagerel $unwind$?update@OBJECT@XGK@@YAXPEAUObject@2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?update2@OBJECT@XGK@@YAXPEAUObject@2@@Z DD imagerel $LN4
	DD	imagerel $LN4+38
	DD	imagerel $unwind$?update2@OBJECT@XGK@@YAXPEAUObject@2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?update3@OBJECT@XGK@@YAXPEAUObject@2@@Z DD imagerel $LN4
	DD	imagerel $LN4+89
	DD	imagerel $unwind$?update3@OBJECT@XGK@@YAXPEAUObject@2@@Z
pdata	ENDS
;	COMDAT __real@bf800000
CONST	SEGMENT
__real@bf800000 DD 0bf800000r			; -1
CONST	ENDS
;	COMDAT __real@3f800000
CONST	SEGMENT
__real@3f800000 DD 03f800000r			; 1
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?update3@OBJECT@XGK@@YAXPEAUObject@2@@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?update2@OBJECT@XGK@@YAXPEAUObject@2@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?update@OBJECT@XGK@@YAXPEAUObject@2@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?trans@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z DD 061201H
	DD	026812H
	DD	08340aH
	DD	07006520aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?init@OBJECT@XGK@@YAXPEAUObject@2@@Z DD 020601H
	DD	030023206H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?update3@OBJECT@XGK@@YAXPEAUObject@2@@Z
_TEXT	SEGMENT
object_addr$ = 48
?update3@OBJECT@XGK@@YAXPEAUObject@2@@Z PROC		; XGK::OBJECT::update3, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 154
$LN4:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
; Line 156
	movss	xmm2, DWORD PTR __real@3f800000
	lea	rdx, QWORD PTR [rcx+96]
	mov	rdi, rcx
	call	QWORD PTR ?makeTransValue@MAT4@DATA@XGK@@3P6AXPEAX0M@ZEA ; XGK::DATA::MAT4::makeTransValue
; Line 157
	lea	rdx, QWORD PTR [rdi+64]
	mov	rcx, rdi
	call	QWORD PTR ?preRotQuat@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA ; XGK::DATA::MAT4::preRotQuat
; Line 158
	movss	xmm2, DWORD PTR __real@bf800000
	lea	rdx, QWORD PTR [rdi+96]
	mov	rcx, rdi
	call	QWORD PTR ?preTransValue@MAT4@DATA@XGK@@3P6AXPEAX0M@ZEA ; XGK::DATA::MAT4::preTransValue
; Line 159
	lea	rdx, QWORD PTR [rdi+80]
	mov	rcx, rdi
; Line 161
	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
; Line 159
	rex_jmp	QWORD PTR ?preTrans@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA ; XGK::DATA::MAT4::preTrans
?update3@OBJECT@XGK@@YAXPEAUObject@2@@Z ENDP		; XGK::OBJECT::update3
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?update2@OBJECT@XGK@@YAXPEAUObject@2@@Z
_TEXT	SEGMENT
object_addr$ = 48
?update2@OBJECT@XGK@@YAXPEAUObject@2@@Z PROC		; XGK::OBJECT::update2, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 147
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
; Line 149
	lea	rdx, QWORD PTR [rcx+80]
	mov	rbx, rcx
	call	QWORD PTR ?makeTrans@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA ; XGK::DATA::MAT4::makeTrans
; Line 150
	lea	rdx, QWORD PTR [rbx+64]
	mov	rcx, rbx
; Line 152
	add	rsp, 32					; 00000020H
	pop	rbx
; Line 150
	rex_jmp	QWORD PTR ?preRotQuat@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA ; XGK::DATA::MAT4::preRotQuat
?update2@OBJECT@XGK@@YAXPEAUObject@2@@Z ENDP		; XGK::OBJECT::update2
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?update@OBJECT@XGK@@YAXPEAUObject@2@@Z
_TEXT	SEGMENT
object_addr$ = 48
?update@OBJECT@XGK@@YAXPEAUObject@2@@Z PROC		; XGK::OBJECT::update, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 140
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
; Line 142
	lea	rdx, QWORD PTR [rcx+64]
	mov	rbx, rcx
	call	QWORD PTR ?makeRotQuat@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA ; XGK::DATA::MAT4::makeRotQuat
; Line 143
	lea	rdx, QWORD PTR [rbx+80]
	mov	rcx, rbx
; Line 145
	add	rsp, 32					; 00000020H
	pop	rbx
; Line 143
	rex_jmp	QWORD PTR ?preTrans@MAT4@DATA@XGK@@3P6AXPEAX0@ZEA ; XGK::DATA::MAT4::preTrans
?update@OBJECT@XGK@@YAXPEAUObject@2@@Z ENDP		; XGK::OBJECT::update
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?transZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
value$ = 16
?transZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::transZ, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 135
	addss	xmm1, DWORD PTR [rcx+88]
	movss	DWORD PTR [rcx+88], xmm1
; Line 136
	ret	0
?transZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::transZ
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?setTransZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
value$ = 16
?setTransZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::setTransZ, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 130
	movss	DWORD PTR [rcx+88], xmm1
; Line 131
	ret	0
?setTransZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::setTransZ
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?transY@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
value$ = 16
?transY@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::transY, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 123
	addss	xmm1, DWORD PTR [rcx+84]
	movss	DWORD PTR [rcx+84], xmm1
; Line 124
	ret	0
?transY@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::transY
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?setTransY@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
value$ = 16
?setTransY@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::setTransY, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 118
	movss	DWORD PTR [rcx+84], xmm1
; Line 119
	ret	0
?setTransY@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::setTransY
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?transX@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
value$ = 16
?transX@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::transX, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 111
	addss	xmm1, DWORD PTR [rcx+80]
	movss	DWORD PTR [rcx+80], xmm1
; Line 112
	ret	0
?transX@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::transX
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?setTransX@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
value$ = 16
?setTransX@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::setTransX, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 106
	movss	DWORD PTR [rcx+80], xmm1
; Line 107
	ret	0
?setTransX@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::setTransX
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?trans@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z
_TEXT	SEGMENT
object_addr$ = 64
vector_addr$ = 72
value$ = 80
?trans@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z PROC		; XGK::OBJECT::trans, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 95
$LN4:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rdi, rcx
	movaps	XMMWORD PTR [rsp+32], xmm6
; Line 97
	add	rcx, 112				; 00000070H
	movaps	xmm6, xmm2
	call	?copy@VEC4@DATA@XGK@@YAXPEAX0@Z		; XGK::DATA::VEC4::copy
; Line 98
	movaps	xmm1, xmm6
	lea	rcx, QWORD PTR [rdi+112]
	call	QWORD PTR ?muls@VEC4@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::VEC4::muls
; Line 99
	lea	rcx, QWORD PTR [rdi+80]
	lea	rdx, QWORD PTR [rdi+112]
; Line 100
	mov	rbx, QWORD PTR [rsp+64]
	movaps	xmm6, XMMWORD PTR [rsp+32]
	add	rsp, 48					; 00000030H
	pop	rdi
; Line 99
	rex_jmp	QWORD PTR ?add@VEC4@DATA@XGK@@3P6AXPEAX0@ZEA ; XGK::DATA::VEC4::add
?trans@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z ENDP		; XGK::OBJECT::trans
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?setTrans@OBJECT@XGK@@YAXPEAUObject@2@PEAX@Z
_TEXT	SEGMENT
object_addr$ = 8
vector_addr$ = 16
?setTrans@OBJECT@XGK@@YAXPEAUObject@2@PEAX@Z PROC	; XGK::OBJECT::setTrans, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 92
	add	rcx, 80					; 00000050H
	jmp	?copy@VEC4@DATA@XGK@@YAXPEAX0@Z		; XGK::DATA::VEC4::copy
?setTrans@OBJECT@XGK@@YAXPEAUObject@2@PEAX@Z ENDP	; XGK::OBJECT::setTrans
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?postRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
angle$ = 16
?postRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::postRotZ, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 85
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?postRotZ@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::QUAT::postRotZ
?postRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::postRotZ
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?preRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
angle$ = 16
?preRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::preRotZ, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 80
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?preRotZ@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::QUAT::preRotZ
?preRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::preRotZ
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?setRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
angle$ = 16
?setRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::setRotZ, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 75
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?makeRotZ@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::QUAT::makeRotZ
?setRotZ@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::setRotZ
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?postRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
angle$ = 16
?postRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::postRotY, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 68
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?postRotY@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::QUAT::postRotY
?postRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::postRotY
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?preRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
angle$ = 16
?preRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::preRotY, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 63
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?preRotY@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::QUAT::preRotY
?preRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::preRotY
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?setRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
angle$ = 16
?setRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::setRotY, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 58
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?makeRotY@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::QUAT::makeRotY
?setRotY@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::setRotY
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?postRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
angle$ = 16
?postRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::postRotX, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 50
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?postRotX@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::QUAT::postRotX
?postRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::postRotX
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?preRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
angle$ = 16
?preRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::preRotX, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 44
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?preRotX@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::QUAT::preRotX
?preRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::preRotX
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?setRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z
_TEXT	SEGMENT
object_addr$ = 8
angle$ = 16
?setRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z PROC		; XGK::OBJECT::setRotX, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 39
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?makeRotX@QUAT@DATA@XGK@@3P6AXPEAXM@ZEA ; XGK::DATA::QUAT::makeRotX
?setRotX@OBJECT@XGK@@YAXPEAUObject@2@M@Z ENDP		; XGK::OBJECT::setRotX
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?postRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z
_TEXT	SEGMENT
object_addr$ = 8
vector_addr$ = 16
angle$ = 24
?postRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z PROC	; XGK::OBJECT::postRot, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 32
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?postRot@QUAT@DATA@XGK@@3P6AXPEAX0M@ZEA ; XGK::DATA::QUAT::postRot
?postRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z ENDP	; XGK::OBJECT::postRot
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?preRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z
_TEXT	SEGMENT
object_addr$ = 8
vector_addr$ = 16
angle$ = 24
?preRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z PROC	; XGK::OBJECT::preRot, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 27
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?preRot@QUAT@DATA@XGK@@3P6AXPEAX0M@ZEA ; XGK::DATA::QUAT::preRot
?preRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z ENDP	; XGK::OBJECT::preRot
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?setRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z
_TEXT	SEGMENT
object_addr$ = 8
vector_addr$ = 16
angle$ = 24
?setRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z PROC	; XGK::OBJECT::setRot, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 22
	add	rcx, 64					; 00000040H
	rex_jmp	QWORD PTR ?makeRot@QUAT@DATA@XGK@@3P6AXPEAX0M@ZEA ; XGK::DATA::QUAT::makeRot
?setRot@OBJECT@XGK@@YAXPEAUObject@2@PEAXM@Z ENDP	; XGK::OBJECT::setRot
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?init@OBJECT@XGK@@YAXPEAUObject@2@@Z
_TEXT	SEGMENT
object_addr$ = 48
?init@OBJECT@XGK@@YAXPEAUObject@2@@Z PROC		; XGK::OBJECT::init, COMDAT
; File E:\reps\denis-belov\xgk\src\object\object.cpp
; Line 10
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
; Line 12
	call	?ident@MAT4@DATA@XGK@@YAXPEAX@Z		; XGK::DATA::MAT4::ident
; Line 13
	lea	rcx, QWORD PTR [rbx+64]
	call	?ident@QUAT@DATA@XGK@@YAXPEAX@Z		; XGK::DATA::QUAT::ident
; Line 14
	lea	rcx, QWORD PTR [rbx+80]
; Line 16
	add	rsp, 32					; 00000020H
	pop	rbx
; Line 14
	jmp	?reset@VEC4@DATA@XGK@@YAXPEAX@Z		; XGK::DATA::VEC4::reset
?init@OBJECT@XGK@@YAXPEAUObject@2@@Z ENDP		; XGK::OBJECT::init
_TEXT	ENDS
END
